VERSION=8.0.2-0.5
PACKAGE=zcs-core-libs
MAINTAINER=Enrico Weigelt <enrico.weigelt@vnc.biz>
SECTION=free/zcs-base
PRIORITY=optional
DEPENDS=
DESCRIPTION=Makes ZCS core libraries available in the jsp containers
REDMINE_UPLOAD_PROJECT=zcs-core-libs
REDMINE_UPLOAD_URL=https://redmine.vnc.biz/redmine/
LICENSE=LGPLv2
FORCE_ZIMBRA_BASE=ironmaiden
